### ISSUE TITLE
Clarification on kubecfg's future

### ISSUE THREAD

**Issue by SirensOfTitan** [bitnami/kubecfg#247]
Really sorry to noise up the issue list here, but I figure an answer here is good for everyone.  

With `kubecfg` and `ksonnet` sitting in the same organization on GitHub, I'm wondering whether `kubecfg` is going to get archived or deprecated alongside `ksonnet` per this announcement here:
https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/

**Comment by anguslees** [comment]
Thanks for the reminder!  I have answer this a number of times on #ksonnet slack channel, but not yet in a way that was visible to github users:

`kubecfg` is very much alive and well!  The VMware/Heptio announcement only covers ksonnet/ksonnet and ksonnet/ksonnet-lib (and closely related projects).

The plan is to move ksonnet/kubecfg to bitnami/kubecfg to make this clearer real soon now.  This will change the URL (obviously) and the go import statements similarly, but otherwise the VMware announcement has no impact on kubecfg.  When the move happens, GitHub should leave an HTTP redirect behind - so for now you should continue to point people to the existing GitHub ksonnet/kubecfg URL.

(I will use this issue to track the project move.)

**Comment by anguslees** [comment]
- [X] Rename github repo
- [ ] Rename golang imports
- [ ] Fix SaaS integrations (travis-ci, etc)

**Comment by anguslees** [comment]
I think we've completed all the above action items (other than "Profit", still working on that one).  Closing.
